### ISSUE TITLE
IndexError: invalid index of a 0-dim tensor. 

### ISSUE THREAD

**Issue by qige96** [mihaela-stoian/ROAD-R-2023-Challenge#1]
Hi,

I tried to run the notebook `challenge_road_r_2023.ipynb` and got the following error.
```
[INFO: train.py:   55]: EXPERIMENT NAME:: resnet50I3D512-Pkinetics-b4s8x1x1-roadt1-h3x3x3-07-15-19-51-36x
[INFO: train.py:   56]: Training FPN with resnet50 + I3D as backbone 
LR at epoch 1 is 0.0041
/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/content/ROAD-R-2023-Challenge/main.py", line 316, in <module>
    main()
  File "/content/ROAD-R-2023-Challenge/main.py", line 307, in main
    train(args, net, mixed_train_dataset, val_dataset)
  File "/content/ROAD-R-2023-Challenge/train.py", line 86, in train
    iteration = run_train(args, train_data_loader, net, optimizer, epoch, iteration)
  File "/content/ROAD-R-2023-Challenge/train.py", line 153, in run_train
    loc_loss_dict[type_elem].append(mix_loc_loss[i])
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number
```
Any one has any idea what is going wrong?

---

**Versions of important packages**
- Python 3.10.12
- numpy 1.22.4
- torch 2.0.1+cu118

**Note** that:
1. I passed an extra argument `--MODEL_TYPE="I3D"` because there is no `RCGRU` in the default provided kinetics weights 
2. I commented out the [train.py#L23](https://github.com/mihaela-stoian/ROAD-R-2023-Challenge/blob/main/train.py#L23) because it triggered the `SameFileError`:
```
Traceback (most recent call last):
  File "/content/ROAD-R-2023-Challenge/main.py", line 316, in <module>
    main()
  File "/content/ROAD-R-2023-Challenge/main.py", line 307, in main
    train(args, net, mixed_train_dataset, val_dataset)
  File "/content/ROAD-R-2023-Challenge/train.py", line 63, in train
    args, optimizer, scheduler = setup_training(args, net)
  File "/content/ROAD-R-2023-Challenge/train.py", line 23, in setup_training
    utils.copy_source(source_dir)
  File "/content/ROAD-R-2023-Challenge/modules/utils.py", line 75, in copy_source
    shutil.copy2(os.path.join(dirpath, file), source_dir)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 234, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: './experiments/task1/road/logic-ssl_cache_None_0.0/resnet50I3D512-Pkinetics-b4s8x1x1-roadt1-h3x3x3-07-15-20-01-49x/source/blocks.py' and './experiments//task1/road/logic-ssl_cache_None_0.0/resnet50I3D512-Pkinetics-b4s8x1x1-roadt1-h3x3x3-07-15-20-01-49x//source/blocks.py' are the same file
```

**Comment by mihaela-stoian** [comment]
Hi!

By "the notebook challenge_road_r_2023.ipynb", do you mean "ROAD-R_Task1.ipynb"?
Could you please give more details regarding the IndexError you got?
E.g. shapes of images, gt_boxes, gt_labels and other tensors used by the neural network?

Changing the MODEL_TYPE from "RCGRU" to "I3D" should work fine, so that's not a problem.
Also, many thanks for pointing out the RCGRU kinetics weights are missing. I have now updated the repository to include the relevant links (kinetics-pt/get_kinetics_weights.sh) from which you can download RCGRU and other models.

Regarding the SameFileError, this is caused by having the experiments directory inside the repository directory. The jupyter notebooks now provide as example EXPDIR="../experiments/". If you'd like to access the experiments from the repository directory, you could create a symbolic link.

**Comment by qige96** [comment]
Hello,

Yes, I mean the "ROAD-R_Task1.ipynb". Thanks for adding the "RCGRU" weights. And I connfirm that using `EXPDIR="../experiments/"` can get rid of the `SameFileError`. 

I added print statements in the `run_train` function of `train.py` to show the shapes of important tensors, including the shapes `images`, `gt_boxes`, `gt_labels`, `mix_loc_loss`, and `mix_conf_loss`. Here are the outputs:

```
[INFO: train.py:   55]: EXPERIMENT NAME:: resnet50RCGRU512-Pkinetics-b4s8x1x1-roadt1-h3x3x3-07-16-15-52-57x
[INFO: train.py:   56]: Training FPN with resnet50 + RCGRU as backbone 
LR at epoch 1 is 0.0041

images.shape: torch.Size([4, 3, 8, 512, 704]) 
gt_boxes.shape torch.Size([4, 8, 9, 4]) 
gt_labels.shape: torch.Size([4, 8, 9, 42]) 
counts: tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [9, 9, 9, 9, 9, 9, 9, 9],
        [4, 4, 4, 4, 6, 6, 6, 6],
        [3, 3, 3, 4, 4, 4, 4, 4]], device='cuda:0') 
img_indexs: [995, 513, 2152, 1838]
/usr/local/lib/python3.10/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

mix_loc_loss.shape: torch.Size([]) 
mix_conf_loss.shape: torch.Size([]) 
selected_is_ulb.shape: torch.Size([4])

mix_loc_loss: tensor(1.1014, device='cuda:0', grad_fn=<DivBackward0>) 
mix_conf_loss: tensor(0.5961, device='cuda:0', grad_fn=<DivBackward0>) 
selected_is_ulb tensor([False, False, False, False], device='cuda:0')
Traceback (most recent call last):
  File "/content/ROAD-R-2023-Challenge/main.py", line 316, in <module>
    main()
  File "/content/ROAD-R-2023-Challenge/main.py", line 307, in main
    train(args, net, mixed_train_dataset, val_dataset)
  File "/content/ROAD-R-2023-Challenge/train.py", line 86, in train
    iteration = run_train(args, train_data_loader, net, optimizer, epoch, iteration)
  File "/content/ROAD-R-2023-Challenge/train.py", line 162, in run_train
    loc_loss_dict[type_elem].append(mix_loc_loss[i])
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number
```

Seems that the error was raised because the `mix_loc_loss` is a single-values, 0-dim tensor but was treated as a 1-dim tensor storing multiple values. 

`mix_loc_loss` is the [output](https://github.com/mihaela-stoian/ROAD-R-2023-Challenge/blob/main/train.py#L141) of [RetinaNet](https://github.com/mihaela-stoian/ROAD-R-2023-Challenge/blob/main/models/retinanet.py#L118), essentially a [FocalLoss](https://github.com/mihaela-stoian/ROAD-R-2023-Challenge/blob/main/models/retinanet.py#L81),  compuated as a [smooth_l1_loss](https://github.com/mihaela-stoian/ROAD-R-2023-Challenge/blob/main/modules/detection_loss.py#L152) that always get [summed up](https://github.com/mihaela-stoian/ROAD-R-2023-Challenge/blob/main/modules/detection_loss.py#L24) or meaned out along all dimensions.

---

Some more details: I run my [notebook](https://colab.research.google.com/drive/1qN--j6XgGvcuVK9GCLu-diMLqUv0aPXx#scrollTo=wYDBvZ7RGFMv) in the Colab environment.

![image](https://github.com/mihaela-stoian/ROAD-R-2023-Challenge/assets/22453752/5a9ef9bc-f098-4d81-97f8-d9ebc694bf4a)

The images and the `road_trainval_v1.0.json` is trimmed to include only the 3 videos, to save time.

---

Here is my adapted `run_train` function with print statements
```python
def run_train(args, train_data_loader, net, optimizer, epoch, iteration):

    batch_time = AverageMeter()
    data_time = AverageMeter()
    losses = {'gt': AverageMeter(), 'ulb': AverageMeter()}
    loc_losses = {'gt': AverageMeter(), 'ulb': AverageMeter()}
    cls_losses = {'gt': AverageMeter(), 'ulb': AverageMeter()}
    req_losses = {'gt': AverageMeter(), 'ulb': AverageMeter()}
    torch.cuda.synchronize()
    start = time.perf_counter()

    if args.LOGIC is not None:
        Cplus, Cminus = compute_req_matrices(args)

    # for internel_iter, (images, gt_boxes, gt_labels, ego_labels, counts, img_indexs, wh) in enumerate(train_data_loader):
    for internel_iter, (mix_images, mix_gt_boxes, mix_gt_labels, mix_counts, mix_img_indexs, mix_wh, _, _, mix_is_ulb) in enumerate(train_data_loader):
        if args.DEBUG_num_iter and internel_iter > 22:
            logger.info('DID 5 ITERATIONS IN TRAIN, break.... for debugging only')
            break

        images = mix_images.cuda(0, non_blocking=True)
        gt_boxes = mix_gt_boxes.cuda(0, non_blocking=True)
        gt_labels = mix_gt_labels.cuda(0, non_blocking=True)
        counts = mix_counts.cuda(0, non_blocking=True)
        img_indexs = mix_img_indexs

# ========================== My Print Statements ===============================
        print('\nimages.shape:', images.shape, 
          '\ngt_boxes.shape', gt_boxes.shape, 
          '\ngt_labels.shape:', gt_labels.shape, 
          '\ncounts:', counts, 
          '\nimg_indexs:', img_indexs)
# ==================================================================================

        loc_loss_dict = {'gt': [], 'ulb': []}
        conf_loss_dict = {'gt': [], 'ulb': []}
        req_loss_dict = {'gt': [], 'ulb': []}

        iteration += 1
        if args.LOGIC is not None:
            Cplus = Cplus.cuda(0, non_blocking=True)
            Cminus = Cminus.cuda(0, non_blocking=True)
        data_time.update(time.perf_counter() - start)


        mix_mask_is_ulb = torch.tensor([all(mix_is_ulb[b]) for b in range(mix_images.shape[0])])

        # forward
        torch.cuda.synchronize()

        # print(images.size(), anchors.size())
        optimizer.zero_grad()
        # pdb.set_trace()

        if args.LOGIC is None:
            (mix_loc_loss, mix_conf_loss), selected_is_ulb = net(images, gt_boxes, gt_labels, counts, img_indexs, is_ulb=mix_mask_is_ulb)
            # Mean over the losses computed on the different GPUs
            loc_loss, conf_loss = mix_loc_loss.mean(), mix_conf_loss.mean()
            loss = loc_loss + conf_loss
        else:
            (mix_loc_loss, mix_conf_loss, mix_req_loss), selected_is_ulb = net(images, gt_boxes, gt_labels, counts, img_indexs, logic=args.LOGIC, Cplus=Cplus, Cminus=Cminus, is_ulb=mix_mask_is_ulb)
            # Mean over the losses computed on the different GPUs
            loc_loss, conf_loss, req_loss = mix_loc_loss.mean(), mix_conf_loss.mean(), mix_req_loss.mean()
            loss = loc_loss + conf_loss + args.req_loss_weight * req_loss

# ========================== My Print Statements ===============================
        print('\nmix_loc_loss.shape:', mix_loc_loss.shape, 
            '\nmix_conf_loss.shape:', mix_conf_loss.shape, 
            '\nselected_is_ulb.shape:', selected_is_ulb.shape)
        print('\nmix_loc_loss:', mix_loc_loss, 
            '\nmix_conf_loss:', mix_conf_loss, 
            '\nselected_is_ulb', selected_is_ulb)
# ==================================================================================

        for i, elem in enumerate(selected_is_ulb):
            type_elem = 'ulb' if elem else 'gt'
            loc_loss_dict[type_elem].append(mix_loc_loss[i])
            conf_loss_dict[type_elem].append(mix_conf_loss[i])
            if args.LOGIC is not None:
                req_loss_dict[type_elem].append(mix_req_loss[i])

        loss.backward()
        optimizer.step()

        for elem in mix_mask_is_ulb.unique():
            type_elem = 'ulb' if elem else 'gt'

            loc_loss_dict[type_elem] = torch.tensor(loc_loss_dict[type_elem]).mean()
            conf_loss_dict[type_elem] = torch.tensor(conf_loss_dict[type_elem]).mean()
   # omit more ......
```

**Comment by mihaela-stoian** [comment]
Hi,

Thank you for the detailed description of the error!

The issue should be fixed now. Please let us know if the program is running after pulling the latest version of the repository.

The code that was causing the problem is only used for logging separately the losses for the unlabelled and labelled samples (that are mixed in different proportions in each batch; if the unlabelled data was not used during the training, the error still appeared).
When the number of GPUs is equal to the batch size (as recommended in the original [3D-RetinaNet](https://github.com/gurkirt/3D-RetinaNet/tree/master#training-3d-retinanet) repository, e.g. 4 GPUs, each with at least 10GB RAM, for a batch size of 4), the code allows for directly separating the unlabelled and labelled samples in a batch, and thus, for easily logging their separate losses in tensorboard. Our initial code heavily relied on this assumption (although the code can definitely be run on a single GPU!).
The latest code version stores the losses for unlabelled and labelled samples together, whenever the number of gpus is different from the provided batch size. Logging the losses separately only serves an informative role, rather than a functional one. In other words, logging separately the losses for the unlabelled and labelled samples would only provide some indication of how the model is doing on each type of samples. The learning of the model is not affected by this. 

Please note, if you are running the code on a single GPU, Google Colab offers the Pro+ plan with 1 GPU of 52GB RAM. We also have [grants](https://sites.google.com/view/road-r/resources?authuser=0#h.td2pszf6i5u9) that can help with acquiring computing units.

**Comment by qige96** [comment]
Hi,

It works! I can run it now. Thank you very much!

And I will try to apply for the grant as well. Thanks for your kind reminders.

Best,
Ricky
