### ISSUE TITLE
When will the test set be released?

### ISSUE THREAD

**Issue by foolhard** [mihaela-stoian/ROAD-R-2023-Challenge#3]
Hello @mihaela-stoian , 

When will the test set for the Road-R 2023 challenge be released? I cannot find the test set yet. 
Will you postpone the challenge deadline because the test set is postponed?

**Comment by mihaela-stoian** [comment]
Hi @foolhard,

Thank you for your question. The test data is available on the [ROAD-R challenge website](https://sites.google.com/view/road-r/faq?authuser=0) for downloading. Please let us know if you have issues downloading it.

Kind regards,
Mihaela

**Comment by foolhard** [comment]
Hi @mihaela-stoian , 

Thanks for your feedback. 

I have downloaded the test data, but I don't find the JSON file like `blank_road_test_v1.0.json` used in the baseline. Where could I download it? 

Best regards.

**Comment by mihaela-stoian** [comment]
Hi @foolhard,

To download the file blank_road_test_v1.0.json, you can use the script found in the repository  [here](https://github.com/mihaela-stoian/ROAD-R-2023-Challenge/blob/main/data/download_blank_test_annotation_file.sh).

I hope this helps! 
Let us know if it worked or if you have other questions.

Kind regards,
Mihaela

**Comment by foolhard** [comment]
Got it. Thanks  a lot.
