### ISSUE TITLE
Postprocessing for Task 1 and Task 2?

### ISSUE THREAD

**Issue by foolhard** [mihaela-stoian/ROAD-R-2023-Challenge#4]
Hi @mihaela-stoian , 

I have some questions about some specific notes in Road-R 2023 challenge:

1. **Task 1**: Can baseline code generate the Top 20 results for task 1? Can I set "GEN_TOPK" to get the top 20 boxes for one frame?
`parser.add_argument('--GEN_TOPK', default=100,  type=int, help='topk at the time of generation')`

2. **Task 2:** [Road-R_Task2.ipynb](https://notebooks.githubusercontent.com/view/ipynb?browser=chrome&bypass_fastly=true&color_mode=auto&commit=de85a5a2b29d4fe9870d50472663130f79499247&device=unknown_device&docs_host=https%3A%2F%2Fdocs.github.com&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d696861656c612d73746f69616e2f524f41442d522d323032332d4368616c6c656e67652f646538356135613262323964346665393837306435303437323636333133306637393439393234372f524f41442d525f5461736b322e6970796e62&logged_in=true&nwo=mihaela-stoian%2FROAD-R-2023-Challenge&path=ROAD-R_Task2.ipynb&platform=windows&repository_id=651642446&repository_type=Repository&version=116) has a postprocessing section, but the link of postprocessing is invalid. Could you update the link?

![image](https://github.com/mihaela-stoian/ROAD-R-2023-Challenge/assets/13057970/780aeb2a-0507-4a98-b20e-b5c0efe0ec06)

Thanks a lot.

**Comment by mihaela-stoian** [comment]
Hi @foolhard,

We have now updated the repository with an example of a postprocessing script for Task 2.

Kind regards,
Mihaela

**Comment by foolhard** [comment]
Hi @mihaela-stoian , 

Thanks for your feedback. I'll try task 2 postprocessing and get back to you later. 

For task 1, I have a question: 

I submitted a val set result to the leaderboard but **got a lower mAP than my local test code**. How do you generate the result for the val set for task 1 in the evaluation server? Could you share the evaluation code for local test?
  
Best regards

**Comment by foolhard** [comment]
Hi @mihaela-stoian 

Regarding task 2 post-processing, I generate the pkl file for val_1 and run post_processing by command:

```
python post_processing.py --file_path ../experiments/ROAD-R_Challenge_t2/task2/road/logic-ssl_cache_Godel_10.0/resnet50SlowFast512-Pkinetics-b8s8x1x1-roadt1-h3x3x3-09-11-10-42-43x/pred_detections-30-08-50_val_1.pkl --requirements_path ../constraints/constraints.txt 
```

But got error:

```
2014-06-26-09-53-12_stereo_centre_02
Traceback (most recent call last):
  File "post_processing.py", line 129, in <module>
    main()
  File "post_processing.py", line 117, in main
    cost, new_assgn, time_elaps = call_solver(requirements_temp_path)            
  File "post_processing.py", line 80, in call_solver
    return float(cost), assignment, time_elapsed    
UnboundLocalError: local variable 'assignment' referenced before assignment
```

Could you help solve it?

**Comment by EGiunchiglia** [comment]
If you have this error, it means that the MaxHS solver is having some troubles. 

We have updated the script so that you can see what is the output of the solver, can you please try to re-run it and share with us the output of the solver?

**Comment by foolhard** [comment]
Hi @EGiunchiglia , 

I update the script and re-run it.  It has errors as below.  Could you please check the issue?


```
root@workspace:/dfs/data/yyq/ROAD-R-2023-Challenge/postprocessing# python post_processing.py --file_path /dfs/share-read-write/chenfeng13/0926/pred_detections-30-08-50_val_1.pkl --requirements_path ../constraints/constraints.txt2014-06-26-09-53-12_stereo_centre_02
Error in processing solver's output
Solver's output:
c MaxHS 3.2.1
c Instance: _temp.txt
c Parameter Settings
c ============================================
c  A: General MaxHS Options
c   bvardecisions = false, fbeq = false, printOptions = true, printBstSoln = false,
c   printSoln = true, version = false, tolerance = 1e-06, cpu-lim = 2147483647,
c   mem-lim = 2147483647, verb = 1, coretype = 0,
c 
c  B: Disjoint Phase Options
c   dsjnt = true, dsjnt-mus-cpu-lim = 10, dsjnt-cpu-lim = 30,
c 
c  C: Seeding Options
c   seed-learnts = true, seedtype = 3, seed-max = 524288, seed-all-limit = 768,
c  
c  D: Sequence of Sat Options
c   lp-harden = true, find-forced = false, improve-model = false, use-ub-mipstart = true,
c   max-cpu-improve-model = 10, max-cpu-before-cplex = 300, relaxfrac = 0.3, optcores-cpu-lim = 10,
c   nonopt = 3, frac-rampup-start = 128, frac-rampup-end = 512, max-cores-before-cplex = 1536,
c   sort-assumps = 0, max-size-improve-model = -1,
c 
c  E: Core Minimization Options
c   mus-min-red = 0.1, mus-cpu-lim = 2.5, mintype = 1, mverb = 0,
c  
c  F: CPLEX Options
c   cplex-tune = false, cplex-min-ticks = 4, cplex-threads = 1,
c 
c  G: CPLEX Solution Pool and Populate Options
c   cplextime-pop-cpu-lim = 7.5, cplex-solnpool-cap = 256, cplex-pop-nsoln = 256, cplex-populate = 1,
c   ub-conflicts = 1,
c 
c  H: Preprocessing Options
c   mx-sat-prepro = false, mx-constrain-hs = true, mx-seed-mxes = true, simplify-only = false,
c   wcnf-harden = true, wcnf-units = true, wcnf-eqs = false, preprocess = true,
c   mx-cpu-lim = 15, mx-transform-mxes = 2, mx-mem-lim = 1536, mx-find-mxes = 3,
c   mx-hs-use-abs = 2,
c 
c  I: Debugging Options
c   dump-prepro = false, cplex-output = false, cplex-wrt-model = false, cplex-data-chk = false,
c  
c  J: MINISAT solver Options
c   assump-reprocess = true, luby = true, rnd-init = false, gc-frac = 0.2,
c   rinc = 2, rnd-seed = 9.16483e+07, rnd-freq = 0, cla-decay = 0.999,
c   var-decay = 0.95, phase-saving = 2, ccmin-mode = 2, rfirst = 100,
c   min-learnts = 0, sverb = 0, averb = 0,
c 
c  K: MINISAT simplifier Options
c   asymm = false, rcheck = false, elim = true, simp-gc-frac = 0.5,
c   grow = 0, cl-lim = 20, sub-lim = 1000
c ============================================
c
```

**Comment by EGiunchiglia** [comment]
Thanks, there was a mistake on our side as we forgot to add the constraints in WDIMACS format in the `constraints` folder. 

You can now find it at: `https://github.com/mihaela-stoian/ROAD-R-2023-Challenge/blob/main/constraints/WDIMACS_requirements.txt`

Also, remember that this code expects the predictions in the Task 2 format, and will have unexpected behaviour when fed with predictions in Task 1 format. 

Please let us know if you incur in any other issue.

**Comment by Lavreniuk** [comment]
Hi @EGiunchiglia ,
postprocessing is working good now, however I get this error (outputs) for the your baseline.
Please help me to solve it.

Evaluating for Task-2
Number of not annotated frames: 1
Number of not annotated frames: 626
Number of not annotated frames: 0
Number of not annotated frames: 0

**Comment by EGiunchiglia** [comment]
Dear participant, 

I cannot find this issue online anymore. I am thus directly replying to you. 

The output you are reporting is not an error, it is an internal check that we added to our evaluation procedure. 

Hope this helps, 
Best regards, 
Eleonora Giunchiglia

**Comment by Lavreniuk** [comment]
Can you please share the error you get?

Best regards,
Eleonora

On 3 Oct 2023, at 16:51, ***@***.*** wrote:

Dear Eleonora,
Thank you for clarification! I have find out it, so deleted the message.
But now, I get another issue when submit for task2 about maximum number of predicted bboxes (more than 100).
in main.py I found that there is a param = 100 for number of bboxes.
I did not change it, I run train command from your tasks2 notebook and after than postprocessing.py.

Could you please help me with this issue?
Or maybe give actual commands to reproduce the baseline, maybe I run something wrong...

Best regards,
Mykola


3 жовтня 2023, 18:36:41, від "Eleonora" ***@***.******@***.***>>:

Dear participant,

I cannot find this issue online anymore. I am thus directly replying to you.

The output you are reporting is not an error, it is an internal check that we added to our evaluation procedure.

Hope this helps,
Best regards,
Eleonora Giunchiglia

**Comment by foolhard** [comment]
@EGiunchiglia , 

I can submit task 2 results correctly with the new post-processing code now. Thanks for your kind support.
