### ISSUE TITLE
Could you release the metric code for Task 1 and 2?

### ISSUE THREAD

**Issue by foolhard** [mihaela-stoian/ROAD-R-2023-Challenge#5]
Hi,

Could you release the metric code for Tasks 1 and 2? 
It's convenient for us to test the val set locally. 

Thanks.

**Comment by EGiunchiglia** [comment]
Unfortunately, that is not possible as we need to limit the number of times participants are able to evaluate their models both on the validation and test set.

**Comment by Lavreniuk** [comment]
hi, @foolhard , have you been able to reproduce the baseline results for task2?

**Comment by EGiunchiglia** [comment]
@Lavreniuk I guess all problems were solved with the new post-processing method. I will thus close the this issue.

**Comment by foolhard** [comment]
Yes, I can submit the results to the leaderboard correctly with the new post-processing code. Thanks for your kindly support.
